import type { Metadata } from "next";
import { Inter, Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { Provider } from "../components/ui/provider";
import { SocketProvider } from "@/components/ui/SocketProvider";
import { Orbitron } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});
const pixelify = Pixelify_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${orbitron.className} `}>
        {" "}
        {/* <SocketProvider> */} {/* Place SocketProvider here */}
        <Provider>
          {children} {/* Your app's content */}
        </Provider>
        {/* </SocketProvider>{" "} */}
        {/* Make sure to close the tag */}
      </body>
    </html>
  );
}
